package app.model.enumeration.attribut;

public enum AttributsEnum {

	BRULURE,FOLIE,FURIE,GELE,NOYADE,PARALYSIE,ASPHYXIE,POISON,FOSSILE,SOMEIL,BOUCLIER,BARIERRE,REGENERATION,SILENCE,KO,ZOMBIE,OBSCURITE,VIE_UP,VIE_DOWN,MANA_UP,MANA_DOWN,
	FORCE_UP,FORCE_DOWN,AGILITE_UP,AGILITE_DOWN,VITESSE_UP,VITESSE_DOWN,DEXTERITE_UP,DEXTERITE_DOWN,PRECISION_UP,PRECISION_DOWN,CONSTITUTION_UP,CONSTITUTION_DOWN,RESISTANCE_UP,
	RESISTANCE_DOWN,INTELIGENCE_UP,INTELIGENCE_DOWN,CHANCE_UP,CHANCE_DOWN;
}
